default_install_hook_types: [pre-commit, commit-msg, post-checkout, post-merge]
default_stages: [pre-commit]

repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.29.1
  hooks:
      - id: commitizen
        stages: [commit-msg]
- repo: local
  hooks:
      - id: unit-tests
        name: unit-tests
        entry: poetry run pytest tests
        language: python
        fail_fast: true
        pass_filenames: false
-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
      - id: poetry-install
        stages: [post-checkout, post-merge]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]